import jwt from 'jsonwebtoken';import {z} from 'zod';import {prisma} from '../utils/prisma.js';import {calculatePoints} from '../utils/points.js';
const joinSchema=z.object({roomCode:z.string().trim().length(5).transform(v=>v.toUpperCase()),nickname:z.string().trim().min(2).max(30),participantId:z.number().int().positive().optional()});
const roomSchema=z.object({roomCode:z.string().trim().length(5).transform(v=>v.toUpperCase())});
const answerSchema=z.object({roomCode:z.string().trim().length(5).transform(v=>v.toUpperCase()),participantId:z.number().int().positive(),optionIds:z.array(z.number().int().positive()).min(1)});
const ackError=(ack,error)=>typeof ack==='function'&&ack({ok:false,error:error.message||'Ошибка сервера'});
async function ownedSession(roomCode,userId){return prisma.quizSession.findFirst({where:{roomCode,quiz:{organizerId:userId}},include:{quiz:{include:{questions:{orderBy:{position:'asc'},include:{options:true}}}}}})}
function safeQuestion(q){return {id:q.id,text:q.text,imageUrl:q.imageUrl,type:q.type,timeLimit:q.timeLimit,points:q.points,options:q.options.sort((a,b)=>a.position-b.position).map(({id,text,position})=>({id,text,position}))}}
async function leaderboard(sessionId){return prisma.participant.findMany({where:{sessionId},select:{id:true,nickname:true,score:true},orderBy:[{score:'desc'},{joinedAt:'asc'}]})}
export function registerQuizSocket(io){
  io.use((socket,next)=>{const token=socket.handshake.auth?.token;if(token)try{socket.user=jwt.verify(token,process.env.JWT_SECRET)}catch{}next()});
  io.on('connection',socket=>{
    socket.on('room:join',async(payload,ack)=>{try{const data=joinSchema.parse(payload);const session=await prisma.quizSession.findUnique({where:{roomCode:data.roomCode}});if(!session||session.status==='FINISHED')throw new Error('Комната недоступна');let participant=data.participantId?await prisma.participant.findFirst({where:{id:data.participantId,sessionId:session.id}}):null;if(participant)participant=await prisma.participant.update({where:{id:participant.id},data:{socketId:socket.id,nickname:data.nickname}});else participant=await prisma.participant.create({data:{nickname:data.nickname,socketId:socket.id,sessionId:session.id}});socket.join(data.roomCode);socket.data.participantId=participant.id;socket.data.roomCode=data.roomCode;io.to(data.roomCode).emit('participant:joined',{participant:{id:participant.id,nickname:participant.nickname},participants:await leaderboard(session.id)});ack?.({ok:true,participant,session:{status:session.status,currentQuestion:session.currentQuestion}})}catch(e){ackError(ack,e)}});
    socket.on('host:join',async(payload,ack)=>{try{if(socket.user?.role!=='ORGANIZER')throw new Error('Нет доступа');const {roomCode}=roomSchema.parse(payload);const session=await ownedSession(roomCode,socket.user.id);if(!session)throw new Error('Комната не найдена');socket.join(roomCode);ack?.({ok:true,session,participants:await leaderboard(session.id)})}catch(e){ackError(ack,e)}});
    socket.on('quiz:start',async(payload,ack)=>{try{if(socket.user?.role!=='ORGANIZER')throw new Error('Нет доступа');const {roomCode}=roomSchema.parse(payload),session=await ownedSession(roomCode,socket.user.id);if(!session)throw new Error('Комната не найдена');const updated=await prisma.quizSession.update({where:{id:session.id},data:{status:'ACTIVE',startedAt:new Date(),currentQuestion:-1}});await prisma.quiz.update({where:{id:session.quizId},data:{status:'ACTIVE'}});io.to(roomCode).emit('quiz:started',{sessionId:updated.id});ack?.({ok:true})}catch(e){ackError(ack,e)}});
    socket.on('question:show',async(payload,ack)=>{try{if(socket.user?.role!=='ORGANIZER')throw new Error('Нет доступа');const {roomCode}=roomSchema.parse(payload),session=await ownedSession(roomCode,socket.user.id);if(!session||session.status!=='ACTIVE')throw new Error('Сессия не запущена');const index=session.currentQuestion+1,q=session.quiz.questions[index];if(!q)throw new Error('Вопросы закончились');const startedAt=new Date();await prisma.quizSession.update({where:{id:session.id},data:{currentQuestion:index,questionStartedAt:startedAt}});io.to(roomCode).emit('question:active',{question:safeQuestion(q),number:index+1,total:session.quiz.questions.length,startedAt:startedAt.toISOString()});ack?.({ok:true,question:safeQuestion(q)})}catch(e){ackError(ack,e)}});
    socket.on('answer:submit',async(payload,ack)=>{try{const data=answerSchema.parse(payload),session=await prisma.quizSession.findUnique({where:{roomCode:data.roomCode},include:{quiz:{include:{questions:{orderBy:{position:'asc'},include:{options:true}}}}}});if(!session||session.status!=='ACTIVE'||!session.questionStartedAt)throw new Error('Сейчас нельзя отвечать');const participant=await prisma.participant.findFirst({where:{id:data.participantId,sessionId:session.id}});if(!participant)throw new Error('Участник не найден');const q=session.quiz.questions[session.currentQuestion];if(!q)throw new Error('Вопрос не найден');const elapsed=Date.now()-session.questionStartedAt.getTime();if(elapsed>q.timeLimit*1000)throw new Error('Время ответа истекло');const valid=q.options.filter(o=>data.optionIds.includes(o.id));if(valid.length!==new Set(data.optionIds).size)throw new Error('Некорректный вариант');const correctIds=q.options.filter(o=>o.isCorrect).map(o=>o.id).sort(),selected=[...data.optionIds].sort();const isCorrect=correctIds.length===selected.length&&correctIds.every((id,i)=>id===selected[i]);const points=calculatePoints({isCorrect,answerTime:elapsed/1000,timeLimit:q.timeLimit,maxPoints:q.points});const answer=await prisma.$transaction(async tx=>{const a=await tx.participantAnswer.create({data:{participantId:participant.id,questionId:q.id,isCorrect,points,answerTimeMs:elapsed,selectedOptions:{create:selected.map(optionId=>({optionId}))}}});await tx.participant.update({where:{id:participant.id},data:{score:{increment:points}}});return a});ack?.({ok:true,answer:{id:answer.id,submitted:true}})}catch(e){ackError(ack,e)}});
    socket.on('question:close',async(payload,ack)=>{try{if(socket.user?.role!=='ORGANIZER')throw new Error('Нет доступа');const {roomCode}=roomSchema.parse(payload),session=await ownedSession(roomCode,socket.user.id);if(!session)throw new Error('Комната не найдена');const q=session.quiz.questions[session.currentQuestion];io.to(roomCode).emit('question:closed',{correctOptionIds:q.options.filter(o=>o.isCorrect).map(o=>o.id),leaderboard:await leaderboard(session.id)});ack?.({ok:true})}catch(e){ackError(ack,e)}});
    socket.on('quiz:finish',async(payload,ack)=>{try{if(socket.user?.role!=='ORGANIZER')throw new Error('Нет доступа');const {roomCode}=roomSchema.parse(payload),session=await ownedSession(roomCode,socket.user.id);if(!session)throw new Error('Комната не найдена');const ranked=await leaderboard(session.id);await prisma.$transaction([prisma.quizResult.deleteMany({where:{sessionId:session.id}}),...ranked.map((p,i)=>prisma.quizResult.create({data:{sessionId:session.id,participantId:p.id,score:p.score,place:i+1}})),prisma.quizSession.update({where:{id:session.id},data:{status:'FINISHED',finishedAt:new Date()}}),prisma.quiz.update({where:{id:session.quizId},data:{status:'FINISHED'}})]);io.to(roomCode).emit('quiz:finished',{leaderboard:ranked});ack?.({ok:true,leaderboard:ranked})}catch(e){ackError(ack,e)}});
  });
}
